name: Job Data Output
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    brnaches:
      - main
      - 'release/**'
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - 'release/**'
      - 'release.*/^'
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone The code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Output Job Data
        uses: actions/upload-artifact@v3
        with:
          name: job-Data
          path: |
            /job/data/disk-files
            $GITHUB_JOB
            $GITHUB_RUN_ID
            $GITHUB_RUN_NUMBER
            $GITHUB_ACTION
            $GITHUB_ACTOR
            $GITHUB_REPOSITORY
            $GITHUB_REF
            $GITHUB_SHA


  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone The code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying ....."
